# Generated by Django 3.1.7 on 2021-05-18 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('data_urodzenia', models.DateField(verbose_name='Data urodzenia')),
                ('data_smierci', models.DateField(verbose_name='Data smierci')),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_gatunku', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jezyk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_jezyka', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('autor', models.ManyToManyField(to='biblioteka.Autor')),
                ('gatunek', models.ManyToManyField(to='biblioteka.Gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wydanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydawnictwo', models.CharField(max_length=100)),
                ('data', models.DateField(verbose_name='Data wydania')),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.ksiazka')),
            ],
        ),
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalny klucz', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('d', 'Dostepna'), ('nd', 'Niedostepna')], default='d', help_text='Dostepnosc', max_length=2)),
                ('jezyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.jezyk')),
                ('ocena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.ocena')),
                ('wydanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.wydanie')),
            ],
        ),
    ]
