# Generated by Django 3.1.7 on 2021-05-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_auto_20210527_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydanie',
            name='data',
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data wydania'),
        ),
    ]
