# Generated by Django 3.1.7 on 2021-05-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_auto_20210527_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wydanie',
            new_name='Wydawnictwo',
        ),
        migrations.RenameField(
            model_name='egzemplarz',
            old_name='wydanie',
            new_name='wydawnictwo',
        ),
        migrations.RenameField(
            model_name='wydawnictwo',
            old_name='wydawnictwo',
            new_name='nazwa_wydawnictwa',
        ),
    ]
