# Generated by Django 3.1.7 on 2021-05-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_auto_20210527_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egzemplarz',
            name='ocena',
        ),
        migrations.AddField(
            model_name='ocena',
            name='egzemplarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.egzemplarz'),
        ),
    ]
